### ISSUE TITLE
Peekaboo test.py error

### ISSUE THREAD

**Issue by MigliS** [scVENUS/PeekabooAV#16]
Hi Felix
There's just another issue I figured out with my peekaboo installation.
I ran the peekaboo `test.py` and got the following output:
- - -
test_attribute_dict (__main__.TestSample) ... ok
test_job_hash_regex (__main__.TestSample) ... ok
test_sample_attributes (__main__.TestSample) ... No handlers could be found for logger "peekaboo.sample"
FAIL
test_sample_attributes_with_meta_info (__main__.TestSample) ... ok
test_sample_without_suffix (__main__.TestSample) ... ok
ERROR
test_1_analysis2db (__main__.TestDatabase) ... ok
test_2_sample_info_fetch (__main__.TestDatabase) ... ok
test_3_sample_info_update (__main__.TestDatabase) ... ok
test_4_fetch_rule_result (__main__.TestDatabase) ... ok
test_5_known (__main__.TestDatabase) ... ok
ERROR

ERROR: tearDownClass (__main__.TestSample)

Traceback (most recent call last):
  File "test.py", line 223, in tearDownClass
    cls.conf.db_con.close()
AttributeError: 'PeekabooDatabase' object has no attribute 'close'

ERROR: tearDownClass (__main__.TestDatabase)

Traceback (most recent call last):
  File "test.py", line 140, in tearDownClass
    cls.conf.db_con.close()
AttributeError: 'PeekabooDatabase' object has no attribute 'close'

FAIL: test_sample_attributes (__main__.TestSample)

Traceback (most recent call last):
  File "test.py", line 183, in test_sample_attributes
    'Ausschlaggebendes Ergebnis laut Datenbank: Datei ist dem System noch nicht bekannt')
AssertionError: u'Ausschlaggebendes Ergebnis laut Datenbank: This is another test case.' != 'Ausschlaggebendes Ergebnis laut Datenbank: Datei ist dem System noch nicht bekannt'

Ran 10 tests in 0.041s

FAILED (failures=1, errors=2)
`

**Comment by MigliS** [comment]
Works fine now. Thank you! (:
