### ISSUE TITLE
Stabilize REST API mode

### ISSUE THREAD

**Issue by michaelweiser** [scVENUS/PeekabooAV#43]
The current REST API mode works but needs additional error handling and testing for exceptional conditions and erros.

**Comment by michaelweiser** [comment]
Peekaboo fails with the following error if the connection to the API cannot be established. Afterwards Peekaboo is in an unresponsive state and does not retry or at least shut down.
```
2018-11-23 15:57:06,345 - urllib3.connectionpool - (MainThread) - DEBUG - Starting new HTTP connection (1): localhost:8090
HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /cuckoo/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f270c0aaa50>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-11-23 15:57:06,349 - urllib3.connectionpool - (MainThread) - DEBUG - Starting new HTTP connection (1): localhost:8090
HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /cuckoo/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f270c0c61d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-11-23 15:57:06,356 - urllib3.connectionpool - (MainThread) - DEBUG - Starting new HTTP connection (1): localhost:8090
HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /cuckoo/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f270c0c60d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/opt/peekaboo/bin/peekaboo", line 11, in <module>
    load_entry_point('PeekabooAV==1.6.1', 'console_scripts', 'peekaboo')()
  File "build/bdist.linux-x86_64/egg/peekaboo/daemon.py", line 297, in run
  File "build/bdist.linux-x86_64/egg/peekaboo/toolbox/cuckoo.py", line 202, in __init__
  File "build/bdist.linux-x86_64/egg/peekaboo/toolbox/cuckoo.py", line 240, in __status
  File "build/bdist.linux-x86_64/egg/peekaboo/toolbox/cuckoo.py", line 236, in __get
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /cuckoo/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f270c0c60d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```
